# react-ui-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-ui
  template:
    metadata:
      labels:
        app: react-ui
    spec:
      containers:
      - name: react-ui
        image: $IMAGE_ID
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

# react-ui-service.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: react-ui
spec:
  selector:
    app: react-ui
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  type: LoadBalancer
