apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: logging
spec:
  replicas: 2
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi